### ISSUE TITLE
Difficulty compiling bookmain.tex

### ISSUE THREAD

**Issue by JASory** [pelegs/maths_book#9]
Likely not an actual issue, but more my unfamilarity with Latex, however when I clone this repository and run "pdflatex bookmain.tex" it gives me "You didn't enable shell escape so it wasn't possible to launch the Inkscape export  for /figures/chapters/tapir_rainbow.svg" and then "Error: File tapir_rainbow_svg-tex.pdf is missing". Is there a workaround on this? {I assume the document calls Inkscape to compile the image as a pdf which is then combined into the main pdf, but have no idea what the setup is required for that. Could you share your setup or how to bypass the error since I'm mostly concerned with the non-image formatting. }

**Comment by JASory** [comment]
Resolved. 

pdflatex --shell-escape bookmain.tex boxes.tex

**Comment by pelegs** [comment]
That should definitely work, however I would advice you to run `make bookmain` in the riot directory, which will utilize `latexmk` to compile the code enough times to have all references, tikz pictures, etc. displayed correctly.
